rockspec_format = "3.0"
package = "tealdoc"
version = "dev-1"
source = {
   url = "git+https://github.com/teal-language/tealdoc.git",
   branch = "main"
}
description = {
   summary = "A documentation generator written in Teal",
   detailed = "Its primary function is to generate documentation for programs written in Teal, but it is extensible enough to support other languages.",
   homepage = "https://github.com/teal-language/tealdoc",
   license = "MIT",
   issues_url = "https://github.com/teal-language/tealdoc/issues"
}
dependencies = {
   "argparse",
   "tl >= 0.24.7",
   "lunamark",
   "luafilesystem",
   "lua-resty-template >= 2.0"
}
build = {
   type = "builtin",
   modules = {
      ["tealdoc"] = "build/tealdoc.lua",
      ["tealdoc.main"] = "build/tealdoc/main.lua",
      ["tealdoc.cli"] = "build/tealdoc/cli.lua",
      ["tealdoc.config"] = "build/tealdoc/config.lua",
      ["tealdoc.comment_parser"] = "build/tealdoc/comment_parser.lua",
      ["tealdoc.default_env"] = "build/tealdoc/default_env.lua",
      ["tealdoc.log"] = "build/tealdoc/log.lua",
      ["tealdoc.parser.teal"] = "build/tealdoc/parser/teal.lua",
      ["tealdoc.parser.markdown"] = "build/tealdoc/parser/markdown.lua",
      ["tealdoc.dump"] = "build/tealdoc/dump.lua",
      ["tealdoc.generator"] = "build/tealdoc/generator.lua",
      ["tealdoc.generator.markdown"] = "build/tealdoc/generator/markdown.lua",
      ["tealdoc.generator.text"] = "build/tealdoc/generator/text.lua",
      ["tealdoc.generator.site"] = "build/tealdoc/generator/site.lua",
      ["tealdoc.generator.site.api"] = "build/tealdoc/generator/site/api.lua",
      ["tealdoc.generator.site.config"] = "build/tealdoc/generator/site/config.lua",
      ["tealdoc.generator.site.examples"] = "build/tealdoc/generator/site/examples.lua",
      ["tealdoc.generator.site.markdown"] = "build/tealdoc/generator/site/markdown.lua",
      ["tealdoc.generator.site.scintillua"] = "build/tealdoc/generator/site/scintillua.lua",
      ["tealdoc.generator.site.types"] = "build/tealdoc/generator/site/types.lua",
      ["tealdoc.generator.site.view"] = "build/tealdoc/generator/site/view.lua",
      ["tealdoc.generator.site.validator"] = "build/tealdoc/generator/site/validator.lua",
      ["tealdoc.generator.site.default_css"] = "build/tealdoc/generator/site/default_css.lua",
      ["tealdoc.generator.site.pico_css"] = "build/tealdoc/generator/site/pico_css.lua",
      ["tealdoc.generator.site.css.tokens"] = "build/tealdoc/generator/site/css/tokens.lua",
      ["tealdoc.generator.site.css.base"] = "build/tealdoc/generator/site/css/base.lua",
      ["tealdoc.generator.site.css.navigation"] = "build/tealdoc/generator/site/css/navigation.lua",
      ["tealdoc.generator.site.css.content"] = "build/tealdoc/generator/site/css/content.lua",
      ["tealdoc.generator.site.css.components"] = "build/tealdoc/generator/site/css/components.lua",
      ["tealdoc.generator.site.css.home"] = "build/tealdoc/generator/site/css/home.lua",
      ["tealdoc.generator.site.css.search_footer"] = "build/tealdoc/generator/site/css/search_footer.lua",
      ["tealdoc.generator.site.css.responsive"] = "build/tealdoc/generator/site/css/responsive.lua",
      ["tealdoc.generator.site.default_js"] = "build/tealdoc/generator/site/default_js.lua",
      ["tealdoc.generator.site.highlighter"] = "build/tealdoc/generator/site/highlighter.lua",
      ["tealdoc.generator.site.page_template"] = "build/tealdoc/generator/site/page_template.lua",
      ["tealdoc.generator.site.templates.layout"] = "build/tealdoc/generator/site/templates/layout.lua",
      ["tealdoc.generator.site.templates.header"] = "build/tealdoc/generator/site/templates/header.lua",
      ["tealdoc.generator.site.templates.content"] = "build/tealdoc/generator/site/templates/content.lua",
      ["tealdoc.generator.site.templates.home"] = "build/tealdoc/generator/site/templates/home.lua",
      ["tealdoc.generator.site.templates.footer"] = "build/tealdoc/generator/site/templates/footer.lua",
      ["tealdoc.generator.html.generator"] = "build/tealdoc/generator/html/generator.lua",
      ["tealdoc.generator.signatures"] = "build/tealdoc/generator/signatures.lua",
      ["tealdoc.generator.html.builder"] = "build/tealdoc/generator/html/builder.lua",
      ["tealdoc.generator.html.default_css"] = "build/tealdoc/generator/html/default_css.lua",
      ["tealdoc.generator.html.detailed_signature_phase"] = "build/tealdoc/generator/html/detailed_signature_phase.lua",
      ["tealdoc.generator.html.default_js"] = "build/tealdoc/generator/html/default_js.lua",
   },
   install = {
      lua = {
         ["tealdoc"] = "src/tealdoc.tl",
         ["tealdoc.main"] = "src/tealdoc/main.tl",
         ["tealdoc.cli"] = "src/tealdoc/cli.tl",
         ["tealdoc.config"] = "src/tealdoc/config.tl",
         ["tealdoc.comment_parser"] = "src/tealdoc/comment_parser.tl",
         ["tealdoc.default_env"] = "src/tealdoc/default_env.tl",
         ["tealdoc.log"] = "src/tealdoc/log.tl",
         ["tealdoc.parser.teal"] = "src/tealdoc/parser/teal.tl",
         ["tealdoc.parser.markdown"] = "src/tealdoc/parser/markdown.tl",
         ["tealdoc.dump"] = "src/tealdoc/dump.tl",
         ["tealdoc.generator"] = "src/tealdoc/generator.tl",
         ["tealdoc.generator.markdown"] = "src/tealdoc/generator/markdown.tl",
         ["tealdoc.generator.text"] = "src/tealdoc/generator/text.tl",
         ["tealdoc.generator.site"] = "src/tealdoc/generator/site.tl",
         ["tealdoc.generator.site.api"] = "src/tealdoc/generator/site/api.tl",
         ["tealdoc.generator.site.config"] = "src/tealdoc/generator/site/config.tl",
         ["tealdoc.generator.site.examples"] = "src/tealdoc/generator/site/examples.tl",
         ["tealdoc.generator.site.markdown"] = "src/tealdoc/generator/site/markdown.tl",
         ["tealdoc.generator.site.scintillua"] = "src/tealdoc/generator/site/scintillua.tl",
         ["tealdoc.generator.site.types"] = "src/tealdoc/generator/site/types.tl",
         ["tealdoc.generator.site.view"] = "src/tealdoc/generator/site/view.tl",
         ["tealdoc.generator.site.validator"] = "src/tealdoc/generator/site/validator.tl",
         ["tealdoc.generator.site.default_css"] = "src/tealdoc/generator/site/default_css.tl",
         ["tealdoc.generator.site.pico_css"] = "src/tealdoc/generator/site/pico_css.tl",
         ["tealdoc.generator.site.assets"] = "src/tealdoc/generator/site/assets/pico.classless-2.1.1.min.css",
         ["tealdoc.generator.site.css.tokens"] = "src/tealdoc/generator/site/css/tokens.tl",
         ["tealdoc.generator.site.css.base"] = "src/tealdoc/generator/site/css/base.tl",
         ["tealdoc.generator.site.css.navigation"] = "src/tealdoc/generator/site/css/navigation.tl",
         ["tealdoc.generator.site.css.content"] = "src/tealdoc/generator/site/css/content.tl",
         ["tealdoc.generator.site.css.components"] = "src/tealdoc/generator/site/css/components.tl",
         ["tealdoc.generator.site.css.home"] = "src/tealdoc/generator/site/css/home.tl",
         ["tealdoc.generator.site.css.search_footer"] = "src/tealdoc/generator/site/css/search_footer.tl",
         ["tealdoc.generator.site.css.responsive"] = "src/tealdoc/generator/site/css/responsive.tl",
         ["tealdoc.generator.site.default_js"] = "src/tealdoc/generator/site/default_js.tl",
         ["tealdoc.generator.site.highlighter"] = "src/tealdoc/generator/site/highlighter.tl",
         ["tealdoc.generator.site.page_template"] = "src/tealdoc/generator/site/page_template.tl",
         ["tealdoc.generator.site.templates.layout"] = "src/tealdoc/generator/site/templates/layout.tl",
         ["tealdoc.generator.site.templates.header"] = "src/tealdoc/generator/site/templates/header.tl",
         ["tealdoc.generator.site.templates.content"] = "src/tealdoc/generator/site/templates/content.tl",
         ["tealdoc.generator.site.templates.home"] = "src/tealdoc/generator/site/templates/home.tl",
         ["tealdoc.generator.site.templates.footer"] = "src/tealdoc/generator/site/templates/footer.tl",
         ["tealdoc.generator.html.generator"] = "src/tealdoc/generator/html/generator.tl",
         ["tealdoc.generator.signatures"] = "src/tealdoc/generator/signatures.tl",
         ["tealdoc.generator.html.builder"] = "src/tealdoc/generator/html/builder.tl",
         ["tealdoc.generator.html.default_css"] = "src/tealdoc/generator/html/default_css.tl",
         ["tealdoc.generator.html.detailed_signature_phase"] = "src/tealdoc/generator/html/detailed_signature_phase.tl",
         ["tealdoc.generator.html.default_js"] = "src/tealdoc/generator/html/default_js.tl",
      },
      bin = {
         "bin/tealdoc"
      }
   }
}
